---
- hosts: 172.31.33.106
  become: yes
  tasks:
    - include_tasks: myfile.yml
    - name: i want to install webserver on ansible node
      apt:
        name: apache2
        state: present
    - name: i want copy myindes file into ansible node side
      template:
        src: myindex.j2
        dest: /var/www/html/index.html

    - name: i want to download remote(internet) files
      get_url:
        url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
        dest: /home/ubuntu/testfile
        force_basic_auth: yes
